export const PROCEDURE_BOARD_ROUTER = {
  REQUEST_EQUIPMENT: '/uikit/request-equipment',
  CAR_LOCATION: '/uikit/car-location',
  ORDER_PRODUCE_PRODUCT: '/uikit/production-orders-new',
  PLANNING_PRODUCE_PRODUCT: '/uikit/production-orders',
  PLANNING_PRODUCE_WAREHOUSE: '/uikit/production-orders-warehouse',
  EXPENDITURE_PLAN: '/uikit/expenditure-plan',
  MANUFACTURE_ORDER: '/uikit/produce-orders',
  PRODUCE_PRODUCT: '/uikit/production-department',
  LEDGER_IMPORT: '/uikit/import-process',
  REQUEST_EQUIPMENT_ORDER: '/uikit/equipment-order',
  REQUEST_EQUIPMENT_ORDER_FOR_TEST: '/uikit/equipment-order-for-test',
  LEDGER_EXPORT: '/uikit/export-process',
  GATE_PASS: '/uikit/process-gate-pass',
  ADVANCE_PAYMENT: '/uikit/advanced-paymment-pass',
  PAYMENT_PROPOSAL: '/uikit/requesting-paymment-pass',
  OVERTIME:'/uikit/suggest-overtime',
  SIGNATURE_BLOCK:'/uikit/approval-process',
};
