export enum ColumnDataType {
  date = 'date',
  date_time = 'date_time',
  action = 'action',
  text = 'text',
  order = 'order',
  number = 'number',
  checkbox = 'checkbox',
  edit = 'edit',
  tag = 'tag',
  file = 'file',
  currency = 'currency',
  raw= 'raw',
  template='template',
}